steps:
- checkout: microsoft-graph-devx-content
  persistCredentials: true
  displayName: 'Checkout content repo'
  fetchDepth: 1

- pwsh: |
    $today = Get-Date -Format "yyyyMMddHHmm"
    Write-Host "The value of today is $today"
    git config --global user.email "GraphTooling@service.microsoft.com"
    git config --global user.name "Microsoft Graph DevX Tooling"
    cp src/messages/GE.json microsoft-graph-devx-content/messages/
    cd microsoft-graph-devx-content
    git add .
    git commit -m "$today English file transfer"
    git push
  displayName: 'Push English file'