steps:
- checkout: self

- script: echo "##vso[task.setvariable variable=today]$(date +%Y%m%d%H%M)"
  displayName: 'Set current date as env variable'

- pwsh: |
    git config --global user.email "GraphTooling@service.microsoft.com"
    git config --global user.name "Microsoft Graph DevX Tooling"
    git clone https://github.com/microsoftgraph/microsoft-graph-devx-content.git
    cp src/messages/GE.json microsoft-graph-devx-content/messages/
    cd microsoft-graph-devx-content
    git add .
    if git diff-index --quiet HEAD --; then
      echo "No changes to commit"
    else
      git commit -m "$(today) English file transfer"
      git push
    fi
  displayName: 'Push English file'