steps:
- checkout: self

- checkout: github://microsoftgraph/microsoft-graph-devx-content@dev
  persistCredentials: true
  displayName: 'Checkout GitHub Repo'
  name: microsoftgraph

- pwsh: |
    $today = Get-Date -Format "yyyyMMddHHmm"
    Write-Host "The value of today is $today"
    git config --global user.email "GraphTooling@service.microsoft.com"
    git config --global user.name "Microsoft Graph DevX Tooling"
    cp src/messages/GE.json microsoft-graph-devx-content/messages/
    cd microsoft-graph-devx-content
    git add .
    git commit -m "$today English file transfer"
    git push
  displayName: 'Push English file'