steps:
- checkout: self
  persistCredentials: true
  displayName: 'Checkout current repo'

- checkout: microsoft-graph-devx-content
  persistCredentials: true
  displayName: 'Checkout content repo'
  fetchDepth: 1

- pwsh: |
    cp $(Build.SourcesDirectory)/microsoft-graph-explorer-v4/src/messages/GE.json $(Build.SourcesDirectory)/microsoft-graph-devx-content/messages/
  displayName: 'Copy GE.json file'

- pwsh: |
    $today = Get-Date -Format "yyyyMMddHHmm"
    Write-Host "The value of today is $today"
    git config --global user.email "GraphTooling@service.microsoft.com"
    git config --global user.name "Microsoft Graph DevX Tooling"
    cd $(Build.SourcesDirectory)/microsoft-graph-devx-content
    git checkout dev
    git add .
    git commit -m "$today English file transfer"
    git push origin dev
  displayName: 'Push English file'