name: Playwright Tests
on:
  push:
    branches: [ master, dev ]
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  PLAYWRIGHT_TESTS_BASE_URL: "http://localhost:3000/"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright accessibility tests
      run: npx playwright test src/tests/accessibility/ --project=Ms-Edge
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30